* ============================================================================
* analysis.do
* Algorithmic Amplification and Content Bias on Twitter/X
* Evidence from the Musk Acquisition (Oct 27, 2022)
*
* Author : Alex Gamez
* Course : Panel Data & Discrete Choice Models — Spring 2026
* Data   : out/stata_panel.csv  (generated by category_did.py)
*
* Model  : log_dev_it = b0 + b1*Twitter_i + b2*Post_t + b3*(Twitter_i x Post_t) + e_it
*          log_dev = log(y) - log(pre-period mean)  -- same scale for both platforms
*          b3 > 0 : Twitter amplified category beyond organic interest
*          b3 < 0 : Twitter suppressed category below organic interest
* ============================================================================

clear all
capture capture log close
set more off
set scheme s1mono

* ── Globals ──────────────────────────────────────────────────────────────────
global Root   "C:\Users\Alex\OneDrive - The University of Texas at El Paso\Documents\Panel Data 5372\Final Presentation"
global Data   "$Root\out"
global Figs   "$Root\out\figures\stata"

capture mkdir "$Figs"
capture erase "$Root\out\analysis.log"
capture log using "$Root\out\analysis.log", replace


* ============================================================================
* 1. LOAD & PREPARE DATA
* ============================================================================

import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)

* Parse date
gen date_num = date(date, "YMD")
format date_num %td
drop date

* Encode category as numeric (needed for xtset)
encode category, gen(cat_id)

* Unique unit ID: one per (category x platform)
* twitter=1 → Twitter unit;  twitter=0 → Reddit unit
gen unit_id = (cat_id - 1) * 2 + twitter

* Declare panel: unit = category-platform pair, time = date
xtset unit_id date_num

* Treatment date
local treat_date = date("2022-10-27", "YMD")

* Verify post dummy matches treatment date
assert post == (date_num >= `treat_date')

* did = Twitter_i x Post_t  (already in data, but verify)
assert did == (twitter * post)

* Drop rows with missing outcome
drop if missing(log_dev)

* Summary
di "Panel loaded."
xtsum log_dev
tab cat_id twitter


* ============================================================================
* 2. MAIN DiD — POOLED ACROSS ALL CATEGORIES
* ============================================================================
* Pools all 14 categories into one regression.
* Category-platform fixed effects absorb unit-level means.
* Date fixed effects absorb common time shocks.
* Cluster SEs at category level (14 clusters).

di _newline(2) "=== POOLED DiD ==="

* Full two-way FE (preferred spec)
reghdfe log_dev did, absorb(unit_id date_num) vce(cluster cat_id)
estimates store did_pooled

* Simple OLS version (matches Python output exactly — no absorb)
reg log_dev twitter post did, vce(hc3)
estimates store did_simple

* With clustering
reg log_dev twitter post did, cluster(cat_id)
estimates store did_clustered


* ============================================================================
* 3. DiD PER CATEGORY (loop — replicates Python output)
* ============================================================================

di _newline(2) "=== PER-CATEGORY DiD ==="

* Store results
tempfile catresults
postfile cathandle str40 label double b3 se_b3 pval ci_lo ci_hi using `catresults', replace

levelsof cat_id, local(cats)
foreach c of local cats {
    * Get label
    local lbl : label (cat_id) `c'

    * Run DiD for this category only
    capture reg log_dev twitter post did if cat_id == `c', vce(hc3)
    if _rc == 0 {
        local b3    = _b[did]
        local se    = _se[did]
        local pval  = 2 * ttail(e(df_r), abs(`b3' / `se'))
        local ci_lo = `b3' - 1.96 * `se'
        local ci_hi = `b3' + 1.96 * `se'
        post cathandle ("`lbl'") (`b3') (`se') (`pval') (`ci_lo') (`ci_hi')
        di "`lbl':  b3 = " %6.3f `b3' "  p = " %5.3f `pval'
    }
}
postclose cathandle

use `catresults', clear
gsort -b3
list label b3 se_b3 pval ci_lo ci_hi, sep(0) noobs

* Save
export delimited "$Data\stata_did_results.csv", replace
di "Saved: stata_did_results.csv"


* ============================================================================
* 4. COEFFICIENT PLOT — Per-category b3 with 95% CI
* ============================================================================

* Reload results
use `catresults', clear
gsort b3

* Sequence for y-axis
gen rank = _n

* Attach string labels to rank so they appear on y-axis
label define ranklbl 99 ""   // placeholder — overwritten in loop
local n_cats = _N
forvalues i = 1/`n_cats' {
    local lname = label[`i']
    label define ranklbl `i' "`lname'", add modify
}
label values rank ranklbl

graph twoway ///
    (rcap ci_lo ci_hi rank, horizontal lcolor(gs8) lwidth(thin)) ///
    (scatter rank b3, mcolor(navy) msymbol(O) msize(medium)) ///
    , ///
    xline(0, lcolor(black) lwidth(medium) lpattern(solid)) ///
    ytitle("") xtitle("DiD coefficient {&beta}{subscript:3} (log-deviation units)", size(small)) ///
    title("Category DiD: Algorithmic Amplification vs. Suppression", size(medsmall)) ///
    subtitle("Positive = amplified beyond organic interest   Negative = suppressed", size(small)) ///
    note("Outcome: log(share) - log(pre-mean). Control: matched Reddit subreddit. HC3 robust SEs.", size(vsmall)) ///
    ylabel(1(1)`n_cats', valuelabel angle(0) labsize(vsmall)) ///
    xlabel(, labsize(small)) ///
    legend(off) scheme(s1mono)

graph export "$Figs\category_did.png", as(png) replace width(1800)
di "Saved: stata/category_did.png"


* ============================================================================
* 5. EVENT STUDY — Quarterly leads and lags
* ============================================================================

* Reload full panel
import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)
gen date_num = date(date, "YMD")
format date_num %td
drop date
encode category, gen(cat_id)
gen unit_id = (cat_id - 1) * 2 + twitter
xtset unit_id date_num
drop if missing(log_dev)

* quarter is already in the data (binned -8 to +8)
* Generate quarter dummies (omit q = -1 as reference period)
tab quarter

* Leads (pre-treatment): q = -8 to -1
* Lags  (post-treatment): q = 0 to +8
* Reference: q = -1

forvalues q = 1/8 {
    gen lead`q' = (quarter == -`q') * twitter   // pre-treatment quarters
}
forvalues q = 0/8 {
    gen lag`q'  = (quarter ==  `q') * twitter   // post-treatment quarters
}

* Drop reference (lead1 = q=-1 is the omitted category)
drop lead1

global evdummies "lead8 lead7 lead6 lead5 lead4 lead3 lead2 lag0 lag1 lag2 lag3 lag4 lag5 lag6 lag7 lag8"

* Pooled event study with unit + date FEs
reghdfe log_dev $evdummies, absorb(unit_id date_num) vce(cluster cat_id)

* Save coefficients
regsave $evdummies using "$Data\temp_eventstudy.dta", ci level(95) replace
use "$Data\temp_eventstudy.dta", clear
keep var coef ci_lower ci_upper

* Map variable names to quarter numbers
gen quarter = .
replace quarter = -8 if var == "lead8"
replace quarter = -7 if var == "lead7"
replace quarter = -6 if var == "lead6"
replace quarter = -5 if var == "lead5"
replace quarter = -4 if var == "lead4"
replace quarter = -3 if var == "lead3"
replace quarter = -2 if var == "lead2"
replace quarter =  0 if var == "lag0"
replace quarter =  1 if var == "lag1"
replace quarter =  2 if var == "lag2"
replace quarter =  3 if var == "lag3"
replace quarter =  4 if var == "lag4"
replace quarter =  5 if var == "lag5"
replace quarter =  6 if var == "lag6"
replace quarter =  7 if var == "lag7"
replace quarter =  8 if var == "lag8"

* Add reference period (q = -1, coef = 0 by construction)
local n = _N + 1
set obs `n'
replace quarter   = -1  in `n'
replace coef      =  0  in `n'
replace ci_lower  =  0  in `n'
replace ci_upper  =  0  in `n'

sort quarter

* Plot event study
graph twoway ///
    (rarea ci_upper ci_lower quarter, sort color(navy%25) lwidth(none)) ///
    (line coef quarter,   lcolor(navy) lwidth(medium) lpattern(solid)) ///
    (scatter coef quarter, mcolor(navy) msymbol(O) msize(small)) ///
    , ///
    xline(-0.5, lcolor(black) lpattern(dash) lwidth(medium)) ///
    yline(0,    lcolor(gs10)  lpattern(dot)  lwidth(thin)) ///
    xtitle("Quarters relative to treatment (Oct 27, 2022)", size(small)) ///
    ytitle("Twitter {&minus} Reddit gap (log-deviation, pooled)", size(small)) ///
    title("Event Study: Pooled Across All 14 Categories", size(medsmall)) ///
    subtitle("Pre-period quarters near zero validates parallel trends assumption", size(small)) ///
    note("Reference quarter: Q{&minus}1. Shaded = 95% CI. Clustered SEs at category level.", size(vsmall)) ///
    xlabel(-8(1)8, labsize(small)) ///
    legend(off) scheme(s1mono)

graph export "$Figs\event_study_pooled.png", as(png) replace width(1800)
di "Saved: stata/event_study_pooled.png"


* ============================================================================
* 5b. PER-CATEGORY EVENT STUDIES
* ============================================================================

capture mkdir "$Figs\event_study_cat"

* Reload full panel
import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)
gen date_num = date(date, "YMD")
format date_num %td
drop date
encode category, gen(cat_id)
gen unit_id = (cat_id - 1) * 2 + twitter
drop if missing(log_dev)

* Build lead/lag dummies (lead1 = Q-1 is reference, intentionally skipped)
forvalues q = 2/8 {
    gen lead`q' = (quarter == -`q') * twitter
}
forvalues q = 0/8 {
    gen lag`q'  = (quarter ==  `q') * twitter
}

global evdummies "lead8 lead7 lead6 lead5 lead4 lead3 lead2 lag0 lag1 lag2 lag3 lag4 lag5 lag6 lag7 lag8"

* Collect coefficients into a postfile (one row per category-quarter)
tempfile catev
postfile cevh str40 cat_lbl int qtr double coef ci_lo ci_hi using `catev', replace

levelsof cat_id, local(cats)
foreach c of local cats {
    local lbl : label (cat_id) `c'
    capture reg log_dev $evdummies twitter post if cat_id == `c', vce(hc3)
    if _rc != 0 {
        di "Skipping `lbl'"
        continue
    }

    local qnums "-8 -7 -6 -5 -4 -3 -2 0 1 2 3 4 5 6 7 8"
    local k = 0
    foreach v of global evdummies {
        local ++k
        local q   : word `k' of `qnums'
        local b   = _b[`v']
        local se  = _se[`v']
        post cevh ("`lbl'") (`q') (`b') (`b' - 1.96*`se') (`b' + 1.96*`se')
    }
    post cevh ("`lbl'") (-1) (0) (0) (0)
    di "  Collected: `lbl'"
}
postclose cevh

* Plot one graph per category
use `catev', clear

* Set output folder as a local (avoids backslash-backtick path issues)
local evcat_dir "$Figs/event_study_cat"

levelsof cat_lbl, local(catlist)
foreach lbl of local catlist {
    preserve
        keep if cat_lbl == "`lbl'"
        sort qtr
        drop if abs(qtr) == 8

        graph twoway ///
            (rarea ci_hi ci_lo qtr, sort fcolor(gs12) lwidth(none)) ///
            (line  coef   qtr, lcolor(navy) lwidth(medthick) lpattern(solid)) ///
            (scatter coef qtr, mcolor(navy) msymbol(O) msize(small)) ///
            , ///
            xline(-0.5, lcolor(black) lpattern(dash) lwidth(medthick)) ///
            yline(0,    lcolor(gs8)   lpattern(dot)  lwidth(thin)) ///
            xtitle("Quarters relative to Oct 27, 2022", size(small)) ///
            ytitle("Twitter {&minus} Reddit gap (log-deviation)", size(small)) ///
            title("`lbl': Event Study", size(medsmall)) ///
            subtitle("Pre-period near zero validates parallel trends", size(small)) ///
            note("Reference: Q{&minus}1. Shaded = 95% CI (HC3). Q{&plusmn}8 dropped (sparse).", size(vsmall)) ///
            xlabel(-7(1)7, labsize(small)) ///
            legend(off) scheme(s1mono)

        local fname = subinstr("`lbl'", " ", "_", .)
        local fname = subinstr("`fname'", "/", "_", .)
        graph export "`evcat_dir'/`fname'.png", as(png) replace width(1600)
        di "Saved: `lbl'"
    restore
}
di _newline "Per-category event studies → $Figs/event_study_cat/"


* ============================================================================
* 5c. PER-CATEGORY PARALLEL TRENDS PLOTS
* ============================================================================

capture mkdir "$Figs\parallel_trends"

import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)
gen date_num = date(date, "YMD")
format date_num %td
drop date
encode category, gen(cat_id)
gen unit_id = (cat_id - 1) * 2 + twitter
xtset unit_id date_num
drop if missing(log_dev)

local treat_date = date("2022-10-27", "YMD")

* 14-day centered moving average per panel unit
tssmooth ma log_dev_ma = log_dev, window(7 1 6)

* Set output folder as local to avoid backslash-backtick issue in graph export
local pt_dir "$Figs/parallel_trends"

levelsof cat_id, local(cats)
foreach c of local cats {
    local lbl : label (cat_id) `c'

    quietly count if cat_id == `c' & twitter == 1 & !missing(log_dev_ma)
    if r(N) < 30 {
        di "Skipping `lbl' (Twitter sparse)"
        continue
    }
    quietly count if cat_id == `c' & twitter == 0 & !missing(log_dev_ma)
    if r(N) < 30 {
        di "Skipping `lbl' (Reddit sparse)"
        continue
    }

    graph twoway ///
        (line log_dev_ma date_num if cat_id == `c' & twitter == 1, ///
            lcolor(navy) lwidth(medthick) lpattern(solid)) ///
        (line log_dev_ma date_num if cat_id == `c' & twitter == 0, ///
            lcolor(maroon) lwidth(medthick) lpattern(dash)) ///
        , ///
        xline(`treat_date', lcolor(black) lpattern(shortdash) lwidth(medthick)) ///
        yline(0, lcolor(gs10) lpattern(dot) lwidth(thin)) ///
        ytitle("log-deviation from pre-treatment mean", size(small)) ///
        xtitle("") ///
        title("`lbl': Parallel Trends", size(medsmall)) ///
        subtitle("Twitter (navy) vs Reddit (maroon). Vertical = Oct 27, 2022.", size(small)) ///
        note("14-day moving average. Outcome: log(share) - log(pre-period mean).", size(vsmall)) ///
        legend(order(1 "Twitter (treated)" 2 "Reddit (control)") ///
               size(small) pos(11) ring(0) cols(1)) ///
        xlabel(, format(%tdMon_CCYY) labsize(vsmall) angle(30)) ///
        ylabel(, labsize(small)) ///
        scheme(s1mono)

    local fname = subinstr("`lbl'", " ", "_", .)
    local fname = subinstr("`fname'", "/", "_", .)
    graph export "`pt_dir'/`fname'.png", as(png) replace width(1600)
    di "Saved: `lbl'"
}
di _newline "Parallel trends → $Figs/parallel_trends/"


* ============================================================================
* 6. PLACEBO TEST — False treatment dates
* ============================================================================

import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)
gen date_num = date(date, "YMD")
format date_num %td
drop date
encode category, gen(cat_id)
gen unit_id = (cat_id - 1) * 2 + twitter
drop if missing(log_dev)

* Real treatment: Oct 27 2022
local real_treat = date("2022-10-27", "YMD")

* Placebo dates (pre-treatment only)
local placebo1 = date("2021-04-27", "YMD")   // 18 months before
local placebo2 = date("2021-10-27", "YMD")   // 12 months before
local placebo3 = date("2022-04-27", "YMD")   // 6  months before

tempfile placebo_results
postfile ph str20 label double b3 se pval using `placebo_results', replace

foreach d in `placebo1' `placebo2' `placebo3' `real_treat' {
    local dlbl : display %tdCCYY-NN-DD `d'
    gen post_p = (date_num >= `d')
    gen did_p  = twitter * post_p

    capture reg log_dev twitter post_p did_p, vce(hc3)
    if _rc == 0 {
        local b3   = _b[did_p]
        local se   = _se[did_p]
        local pv   = 2 * ttail(e(df_r), abs(`b3' / `se'))
        post ph ("`dlbl'") (`b3') (`se') (`pv')
        di "Placebo `dlbl': b3 = " %6.3f `b3' "  p = " %5.3f `pv'
    }
    drop post_p did_p
}
postclose ph

use `placebo_results', clear
list, sep(0) noobs
di "Placebo: only the real treatment date (2022-10-27) should be significant."


* ============================================================================
* 7. RESULTS SUMMARY TABLE (estout → LaTeX)
* ============================================================================

import delimited "$Data\stata_panel.csv", clear varnames(1) stringcols(1 2)
gen date_num = date(date, "YMD")
format date_num %td
drop date
encode category, gen(cat_id)
gen unit_id = (cat_id - 1) * 2 + twitter
xtset unit_id date_num
drop if missing(log_dev)

eststo clear
quietly eststo m1: reg log_dev twitter post did, vce(hc3)
quietly eststo m2: reg log_dev twitter post did, cluster(cat_id)
quietly eststo m3: reghdfe log_dev did, absorb(unit_id date_num) vce(cluster cat_id)

esttab m1 m2 m3 ///
    using "$Data\stata_results_table.tex", ///
    replace label booktabs ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    keep(did twitter post _cons) ///
    coeflabels(did "Twitter {&times} Post ({&beta}{subscript:3})" ///
               twitter "Twitter" post "Post" _cons "Constant") ///
    mtitles("OLS (HC3)" "OLS (Cluster)" "TWFE (Cluster)") ///
    title("DiD Results: Twitter Algorithmic Amplification After Musk Acquisition") ///
    addnote("Outcome: log-deviation from pre-treatment mean. Positive = amplified, Negative = suppressed.")

di "Saved: stata_results_table.tex"


* ============================================================================
* DONE
* ============================================================================
di _newline(2) "============================================================"
di             "  All Stata analysis complete."
di             "  Outputs:"
di             "    out/stata_panel.csv          -- input panel"
di             "    out/stata_did_results.csv    -- per-category b3"
di             "    out/stata_results_table.tex  -- LaTeX table"
di             "    out/figures/stata/*.png      -- figures"
di             "============================================================"

capture log close
